botToken: "1237370704:AAGFCZ4vevjKdAe3TQbnjS6abBdCfU9SQOQ"
botName: "buscarTuEnvioBot"
webHook:
  domain: ""
  path: ""
  port: ""
  withCert: false
  certPath: ""
  keypath: ""
cache:
  network: "tcp"
  address: "localhost:6379"